{{- if .Values.authorizationPolicy.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.authorizationPolicy.name }}
  namespace: {{ .Values.authorizationPolicy.namespace }}
  {{- with .Values.authorizationPolicy.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.authorizationPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.authorizationPolicy.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  action: {{ .Values.authorizationPolicy.action }}
  {{- if .Values.authorizationPolicy.rules }}
  rules:
    {{- toYaml .Values.authorizationPolicy.rules | nindent 4 }}
  {{- else if eq .Values.authorizationPolicy.action "DENY" }}
  # For DENY policies, we need at least an empty rule to trigger
  rules:
    - {}
  {{- else }}
  {{- with .Values.authorizationPolicy.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
