{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  {{- with .Values.networkPolicy.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.networkPolicy.podSelector }}
  podSelector:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  podSelector: {}
  {{- end }}
  {{- with .Values.networkPolicy.policyTypes }}
  policyTypes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and .Values.networkPolicy.ingress (has "Ingress" .Values.networkPolicy.policyTypes) }}
  {{- with .Values.networkPolicy.ingress.rules }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if and .Values.networkPolicy.egress (has "Egress" .Values.networkPolicy.policyTypes) }}
  {{- with .Values.networkPolicy.egress.rules }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
