apiVersion: v1
entries:
  authorization-policy:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-12-26T11:42:05.988855Z"
    description: A Helm chart for Istio Authorization Policy with default deny in
      istio-system
    digest: d9a857ffcfca846585f7a7d232ca498cdeb8fe20dd73e671b24a977c08e32f96
    home: https://github.com/your-org/charts
    keywords:
    - istio
    - authorization
    - security
    - policy
    maintainers:
    - name: DevOps Team
    name: authorization-policy
    sources:
    - https://github.com/your-org/charts/tree/main/charts/authorization-policy
    type: application
    urls:
    - https://rohkum143.github.io/zero-trust-charts/authorization-policy-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-26T11:42:05.987902Z"
